#ifndef TYPES_H
#define TYPES_H
class Expression;
class Statement;
class Visitor;
class Binary;
class Grouping;
class Literal;
class Unary;
class Ternary;
class Variable;
class Assign;
class Logical;
class Call;
class Get;
class Set;
class ThisExpr;
class StmtExpression;
class Print;
class Var;
class Block;
class IfStmt;
class WhileStmt;
class BreakStmt;
class Function;
class ClassDecl;
class ReturnStmt;
#endif
