#ifndef TYPES_H
#define TYPES_H
class Expression;
class Statement;
class Visitor;
class Binary;
class Grouping;
class Literal;
class Unary;
class Ternary;
class Variable;
class Assign;
class Logical;
class StmtExpression;
class Print;
class Var;
class Block;
class IfStmt;
#endif
